sudo: required
language: minimal
services:
  - docker

script:
  - docker --version && docker-compose --version
  - docker-compose build --build-arg ADDITIONAL_PACKAGES=""
  - docker-compose up -d bastion moto
  - docker-compose run dev test

deploy:
  provider: script
  # All master pushes deploy a 'dev' tag.  If TRAVIS_TAG is set, it also gets deployed along with a 'latest' tag
  script: bash bin/deploy.sh aws-bastion_bastion:latest cloudtruth/aws-bastion dev "${TRAVIS_TAG:+latest}" "${TRAVIS_TAG}"
  on:
    branch: master
