sudo: required
language: minimal
services:
  - docker

script:
  - docker --version && docker-compose --version
  - docker-compose build --build-arg ADDITIONAL_PACKAGES=""
  - docker-compose up -d bastion moto
  - docker-compose run dev test
  - COMPOSE_PROJECT_NAME=aws-bastion-fat docker-compose build bastion

deploy:
  - provider: script
    # Deploy the 'dev' tag on all master pushes
    script: bash bin/deploy.sh aws-bastion_bastion:latest cloudtruth/aws-bastion dev
    on:
      branch: master
  - provider: script
    # Deploy the 'dev-fat' tag for the fat build on all master pushes
    script: bash bin/deploy.sh aws-bastion-fat_bastion:latest cloudtruth/aws-bastion dev-fat
    on:
      branch: master
  - provider: script
    # Deploy the 'latest' and '<git_tag>' tag on all tagged pushes
    script: bash bin/deploy.sh aws-bastion_bastion:latest cloudtruth/aws-bastion latest "${TRAVIS_TAG}"
    on:
      tags: true
  - provider: script
    # Deploy the 'latest-fat' and '<git_tag>-fat' tag for the fat build on all tagged pushes
    script: bash bin/deploy.sh aws-bastion-fat_bastion:latest cloudtruth/aws-bastion latest-fat "${TRAVIS_TAG}-fat"
    on:
      tags: true
