version: '3'
services:

  bastion:
    build:
      context: .
      dockerfile: Dockerfile
    command: "sshd"
    environment:
      SVC_ENV: 'development'
      SVC_PORT: '2222'
      # Pass through aws environment to make it easier to test locally
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
    env_file:
      - .env
    volumes:
      - .:/srv/app
      - bundle_cache:/srv/bundler
    ports:
      - "2222:2222"
    # for pry
    # stdin_open: true
    # tty: true

volumes:
  bundle_cache:
